const AWS_REGION = import.meta.env.VITE_AWS_REGION;
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;
const COGNITO_CLIENT_ID = import.meta.env.VITE_COGNITO_CLIENT_ID;
const COGNITO_APP_DOMAIN = import.meta.env.VITE_COGNITO_APP_DOMAIN;
const COGNITO_REDIRECT_SIGN_IN = import.meta.env.VITE_COGNITO_REDIRECT_SIGN_IN as string;
const COGNITO_REDIRECT_SIGN_OUT = import.meta.env.VITE_COGNITO_REDIRECT_SIGN_OUT as string;
const COGNITO_USERPOOL_ID = import.meta.env.VITE_COGNITO_USERPOOL_ID;
const CCP_URL = import.meta.env.VITE_CCP_URL;
const CCP_LOGIN = import.meta.env.VITE_CCP_LOGIN;
const CCP_API_GATEWAY = import.meta.env.VITE_CCP_API_GATEWAY;
const CCP_AUDIO_CHAT_API_GATEWAY = import.meta.env.VITE_CCP_AUDIO_CHAT_API_GATEWAY;
const KPI_API_GATEWAY = import.meta.env.VITE_KPI_API_GATEWAY;
const CALLER_COUNT_API_GATEWAY = import.meta.env.VITE_CALLER_COUNT_API_GATEWAY;
const DYNAMIC_BUTTONS_API_GATEWAY = import.meta.env.VITE_DYNAMIC_BUTTONS_API_GATEWAY;
const AWS_API_KEY = import.meta.env.VITE_AWS_API_KEY;
const AWS_VPC_ENDPOINT = import.meta.env.VITE_AWS_VPC_ENDPOINT;

export {
  AWS_REGION,
  API_BASE_URL,
  COGNITO_CLIENT_ID,
  COGNITO_APP_DOMAIN,
  COGNITO_REDIRECT_SIGN_IN,
  COGNITO_REDIRECT_SIGN_OUT,
  COGNITO_USERPOOL_ID,
  CCP_URL,
  CCP_LOGIN,
  CCP_API_GATEWAY,
  CCP_AUDIO_CHAT_API_GATEWAY,
  KPI_API_GATEWAY,
  CALLER_COUNT_API_GATEWAY,
  DYNAMIC_BUTTONS_API_GATEWAY,
  AWS_API_KEY,
  AWS_VPC_ENDPOINT
};
